# Generated by Django 4.2 on 2023-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
